### ISSUE TITLE
Erreur de localisation BAN

### ISSUE THREAD

**Issue by RemiDesgrange** [MTES-MCT/Localiser_Parcelle_Adresse_BAN#5]
J'ai une erreur python sur la localisation via la BAN:

```
File "/Users/XXX/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/localiserparcelle/ban_locator_filter.py", line 60, in triggerResult
transformer = self.plugin.getTransformer(4326)
AttributeError: getattribute
```

J'ai ~60 utilisateurs et cette erreur apparait de manière aléatoire. 
Peut-être faut-il s'inspirer du plugin french_locator ?
https://gitlab.com/Oslandia/qgis/french_locator_filter/-/blob/master/french_locator_filter/core/locator_filter.py#L220-L230

**Comment by jdlom** [comment]
@RemiDesgrange quelle est la version de qgis installée ?

**Comment by RemiDesgrange** [comment]
3.22.

**Comment by jdlom** [comment]
@RemiDesgrange une nouvelle version sera bientôt disponible. Est-ce qu'il serait possible de tester et de nous faire une retour ?

**Comment by FERRATON** [comment]
@RemiDesgrange 
La version 3.5.8 est disponible dans le répertoire des plugins du MTE...
